# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

branches:
  except:
    - gh-pages

# We don't need Latex so save time by telling Travis not to install it.
# Via https://docs.travis-ci.com/user/languages/r/#LaTeX-TexLive-Packages
latex: false
r_check_args: "--as-cran --timings"

# Allow build to continue even if a suggested package cannot be installed.
r_check_force_suggests: false

addons:
  apt:
    packages:
      - libmagick++-dev
